Epoch 1/11
2023-05-24 14:30:10.214438: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
74/74 [==============================] - ETA: 0s - loss: 2.6693 - accuracy: 0.2035
2023-05-24 14:30:42.467890: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
74/74 [==============================] - 33s 432ms/step - loss: 2.6693 - accuracy: 0.2035 - val_loss: 1.8100 - val_accuracy: 0.3800
Epoch 2/11
74/74 [==============================] - 34s 454ms/step - loss: 1.7834 - accuracy: 0.3591 - val_loss: 2.2342 - val_accuracy: 0.2600
Epoch 3/11
74/74 [==============================] - 34s 459ms/step - loss: 1.6284 - accuracy: 0.4100 - val_loss: 1.6429 - val_accuracy: 0.4000
Epoch 4/11
74/74 [==============================] - 37s 497ms/step - loss: 1.4754 - accuracy: 0.4630 - val_loss: 1.3677 - val_accuracy: 0.4600
Epoch 5/11
74/74 [==============================] - 33s 448ms/step - loss: 1.3866 - accuracy: 0.5135 - val_loss: 1.4022 - val_accuracy: 0.4600
Epoch 6/11
74/74 [==============================] - 33s 449ms/step - loss: 1.2765 - accuracy: 0.5519 - val_loss: 1.6168 - val_accuracy: 0.4000
Epoch 7/11
74/74 [==============================] - 36s 483ms/step - loss: 1.1798 - accuracy: 0.5810 - val_loss: 1.7101 - val_accuracy: 0.4600
Epoch 8/11
74/74 [==============================] - 34s 457ms/step - loss: 1.1440 - accuracy: 0.6011 - val_loss: 1.1709 - val_accuracy: 0.5800
Epoch 9/11
74/74 [==============================] - 34s 463ms/step - loss: 1.1052 - accuracy: 0.6259 - val_loss: 1.2067 - val_accuracy: 0.5000
Epoch 10/11
74/74 [==============================] - 34s 450ms/step - loss: 1.0076 - accuracy: 0.6541 - val_loss: 1.4593 - val_accuracy: 0.5000
Epoch 11/11
74/74 [==============================] - 34s 460ms/step - loss: 0.9870 - accuracy: 0.6644 - val_loss: 1.3512 - val_accuracy: 0.4400

2023-05-24 14:36:27.267175: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2/2 [==============================] - 0s 103ms/step - loss: 0.9616 - accuracy: 0.5600
[0.9615839123725891, 0.5600000023841858]